version: "3.8"

services:
  mysql:
    build: ./infra/docker/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel}
      - MYSQL_USER=${DB_USER:-laravel}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
    platform: linux/x86_64

  nginx:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./:/backend
    links:
      - php

  php:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/backend
      - /vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_NAME:-laravel}
      - DB_USERNAME=${DB_USER:-laravel}
      - DB_PASSWORD=${DB_PASS:-secret}
    tty: true
