up:
	docker-compose up

down:
	docker-compose down

nginx:
	docker-compose exec nginx /bin/bash

mysql:
	docker-compose exec mysql /bin/bash

php:
	docker-compose exec php /bin/bash

composer:
	docker-compose exec php /bin/bash -c "composer install"
